# Generated by Django 5.2.1 on 2025-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form133',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_nr', models.IntegerField(blank=True, null=True)),
                ('incident_naam', models.CharField(max_length=30)),
                ('datum', models.DateField()),
                ('locatie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form133Next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_nr', models.IntegerField(blank=True, null=True)),
                ('incident_naam', models.CharField(blank=True, max_length=30, null=True)),
                ('locatie', models.CharField(blank=True, max_length=100, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
                ('tijd', models.TimeField()),
                ('team', models.CharField(max_length=50)),
                ('bericht', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('datum', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
