# Generated by Django 5.2.1 on 2025-06-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form133',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form133',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
